def auto_fix_xml_strings(content: str) -> str:
    """
    Safely fixes escaping issues in LLM-generated XML/Markdown strings.
    Specifically replaces improperly escaped single quotes (\\') with a valid single quote (').
    It only replaces \\' if it appears outside of valid JSON-like escaping (though LLMs often output \\' in plain markdown).
    """
    # Replace \\' with ' since \\' is often generated by LLMs in text contexts where it shouldn't be
    return content.replace("\\'", "'")


def auto_fix_markdown(content: str) -> str:
    """
    Fixes common markdown formatting issues.
    For now, ensures strings are normalized, could be extended later.
    """
    return content
